#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d348i9e3jp1c739cnb80-a.frankfurt-postgres.render.com/kursimi
spring.datasource.username=kursimi_user
spring.datasource.password=TRwGoWFnUIGf7eLeUnKRDdV4Cx0rgL4Q